### PR TITLE
Docs for rev3e

### PR DESCRIPTION
**Pull request by jeremy-daily**
I've added Schematics, Altium Files, Bill of materials, and Gerbers for all productions of the CAN Logger 3. 

Please add any instructions for manual rework in README files in the corresponding directory.

### CODE REVIEW

**Review by chris-lute — COMMENTED** [review]
I have no comments on this. It looks correct to me.

**Review by duyvan1995 — APPROVED** [review]

**Review by gannaramu — APPROVED** [review]
I have added the errata information for fixing the 3c boards. Let me know if you want me to do any changes.

**Comment by gannaramu** [comment]
I had a quick question on why we are not having a jumper j2 for the WiFi Module on version 3e

**Comment by jeremy-daily** [comment]
> 
> 
> I had a quick question on why we are not having a jumper j2 for the WiFi Module on version 3e

It's pretty inconvenient. If we know for sure we don't want wireless, then we'll save the money and not install it. Otherwise, we'll want the speed and convenience.

**Pull request merged**
